### ISSUE TITLE
Rendre compatible macOS 

### ISSUE THREAD

**Issue by JefNewTech** [MilesTEG1/Importation-Excel-Donnees-MyPeugeot#2]
J'ai essayer votre fichier sur Mac mais cela ne fonctionne malheureusement pas.

**Comment by MilesTEG1** [comment]
Bonsoir,
Je n'ai malheureusement pas encore eu le temps de travailler sur une version macOS.
La version actuelle ne fonctionne que sous windows.

La version macOS est un projet, mais je ne suis pas sur d'arriver à le mener à terme... Mais si j'y arrive, elle sera partagée ici ;)

**Comment by MilesTEG1** [comment]
Bonjour,
Voilà, une nouvelle version a été envoyée avec le support de macOS.
A tester 😃
